### PR TITLE
Start favfoodupdate

### PR DESCRIPTION
**Pull request by wayfarer1549**

### CODE REVIEW

**Comment by wayfarer1549** [comment]
@drewpatrickboyle Would you review this update? It references issue #4

**Comment by drewpatrickboyle** [comment]
No lettuce please @wayfarer1549

**Comment by wayfarer1549** [comment]
@drewpatrickboyle I have removed the lettuce from the cheeseburger. Do you think it will taste better? It resolves issue #3

**Comment by drewpatrickboyle** [comment]
I think that'll work for me.

**Pull request merged**
