### PR TITLE
Start Add_favorite_movies

### PR DESCRIPTION
**Pull request by wayfarer1549**

### CODE REVIEW

**Comment by wayfarer1549** [comment]
This will close issue #5

**Comment by drewpatrickboyle** [comment]
@wayfarer1549 remove "The Hunt for the Red October" because obviously the book is better than the movie

**Comment by wayfarer1549** [comment]
@drewpatrickboyle I will remove the film, but it's hard to beat Sean Connery!

**Comment by drewpatrickboyle** [comment]
@wayfarer1549 True. Hold if you haven't

**Comment by wayfarer1549** [comment]
@drewpatrickboyle What film do you want on the list?

**Comment by wayfarer1549** [comment]
@drewpatrickboyle I've added Interstellar to the list. This should close issue #5

**Comment by drewpatrickboyle** [comment]
merged commit favorite_movies.txt to master solving #5

**Pull request merged**
